### ISSUE TITLE
Failed test - auxiliary elements are no more in the ouput

### ISSUE THREAD

**Issue by makma** [Kentico/cloud-sdk-swift#18]
There is failed test due to auxiliary elements are no more in the content types endpoint's output.

`Get_content_type_request__getting_content_type_using_content_type_name__returns_content_type_with_correct_name_codename_and_elements, expected to equal <13>, got <12>`

**Comment by petrsvihlik** [comment]
Try to run it again. It might have been caused by https://kentico.atlassian.net/browse/DEL-1356 which is already fixed

**Comment by makma** [comment]
I've solved it with Delivery guys - auxiliary elements are no more in the output - we have to (me) fix the test. I'll do it today.

**Comment by makma** [comment]
Fixed in https://github.com/Kentico/cloud-sdk-swift/pull/20
