### ISSUE TITLE
Strong types for modular content

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-sdk-swift#4]
- be able to use a collection of strongly typed models instead of the `ModularContentElement` type

**Comment by makma** [comment]
It is possible to retrieve modualar content like:
`client.getItem(modelType: Article.self, itemName: "on_roasts", completionHandler: { (isSuccess, itemResponse, error) in
	    if isSuccess {
		    let relatedArticle = itemResponse?.getModularContent(codename: "on_roasts", type: 
    Article.self)
	}
`

**Comment by petrsvihlik** [comment]
great, i see you already documented it. thx!
