### ISSUE TITLE
Easy way to build a query

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-sdk-swift#6]
Implement an easy way to build a query string. It is possible to use the Fluent syntax for parameterization:
* https://github.com/vandadnp/swift-weekly/blob/master/issue05/README.md
* https://en.wikipedia.org/wiki/Fluent_interface#Swift

Try to be consistent with method naming with other languages if possible.

**Acceptance criteria:**
- Have all query parameters implemented to be able to use them by the fluent API.

**Other languages implementations:**
- https://github.com/Kentico/delivery-sdk-java/blob/master/delivery/src/main/java/com/kenticocloud/delivery/DeliveryParameterBuilder.java
- https://github.com/Kentico/delivery-sdk-php/blob/master/src/KenticoCloud/Delivery/QueryParams.php
- https://github.com/Kentico/delivery-sdk-net/tree/master/KenticoCloud.Delivery/QueryParameters

**Comment by akantsevoi** [comment]
Is I understand correct that you want to improve creation of that array:
```
let typeQueryParameter = QueryParameter.init(parameterKey: QueryParameterKey.type, parameterValue: "article")
let languageQueryParameter = QueryParameter.init(parameterKey: QueryParameterKey.language, parameterValue: "es-ES")
let articlesQueryParameters = [typeQueryParameter, languageQueryParameter]
```
?

**Comment by petrsvihlik** [comment]
@akantsevoi  Yes, that's absolutely correct. Currently, it's unnecessarily verbose.
