### ISSUE TITLE
getContentType returns a ContentType object but it has no usable properties

### ISSUE THREAD

**Issue by leeprobert** [Kentico/cloud-sdk-swift#70]
I am trying to retrieve ContentType objects for items in my CMS. In the code I am getting the ContentType object but it has no usable properties (name, codename etc). They are all nil.

Here's a screenshot: https://www.evernote.com/l/AAT49CFVycxKgb9dI3FRiAjckLwUN9osXY4B/image.png

and I have posted something on Stack: https://stackoverflow.com/questions/56873746/kentico-cloud-swift-sdk-contenttype-does-not-have-usable-properties

**Comment by makma** [comment]
Let's solve it on [StackOverflow](https://stackoverflow.com/questions/56873746/kentico-cloud-swift-sdk-contenttype-does-not-have-usable-properties/56876678#56876678).

**Comment by leeprobert** [comment]
I think I understand the issue now, but it has revealed a bigger issue which i wonder if we should open up as a feature request? Retrieving a LinkedItemsElement object only gives you an array of codenames as a value. Maybe it should give you a tuple of the codename and type? Then the user can dynamically map the codenames to their types and grab each of the items.
