### ISSUE TITLE
ImageUrlBuilder class missing from 1.1.0

### ISSUE THREAD

**Issue by leeprobert** [Kentico/cloud-sdk-swift#73]
I don't seem to be getting `ImageUrlBuilder` in v1.1.0.
![Screenshot_17_07_2019__21_02](https://user-images.githubusercontent.com/151336/61407897-b97dae00-a8d6-11e9-80b8-7aa9dd73ab57.jpg)
Am I missing something?

**Comment by makma** [comment]
Hi @leeprobert , yes you are right, probably some issue with building of pod package. I'm going to fix this one and release the new package asap. If you need it urgently, as a quick workaround, you can just copy source code for the SDK into your project. I'll keep you update.

**Comment by makma** [comment]
Hi @leeprobert, there has been released a new 1.2.0 version of the SDK which contains UrlBuilder as well. I hope u like the feature ;)
